### ISSUE TITLE
Broken image link

### ISSUE THREAD

**Issue by champie** [helpshift/helpshift-docs#41]
The image link in helpshift-docs/docs/sdkx-unity/getting-started-ios.mdx:157 seems broken. It's currently using;

    <Image src="/static/books/helpshiftx/copy_keys.png"  width="full" />

I think that line should be;

    <Image src="/static/books/sdkx_ios/copy_keys.png"  width="full" />

**Comment by hs-hritik** [comment]
Thanks, @champie for pointing it out. I'll create a PR to fix this issue asap.
